### ISSUE TITLE
Don't block root inside Docker containers

### ISSUE THREAD

**Issue by twogood** [sindresorhus/sudo-block#6]
When sudo-block is used inside a [Docker](https://www.docker.com/) container, it should probably not block. Everything inside the container runs as the *container root user*, which is not the same as the actual root user on the Docker host.

Checking if running on Docker is as simple as checking for a file called `/.dockerinit` on the file system.

**Comment by sindresorhus** [comment]
Sure, pull request welcome.

**Comment by arthurvr** [comment]
Closing. https://github.com/sindresorhus/sudo-block/pull/7 was merged.
