### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/sudo-block#8]
Would it make sense to block when it's run as Administrator user on Windows? It's not exactly the same as Unix root user, but the principle applies; users shouldn't be running user commands with it.

Could just use [`is-elevated`](https://github.com/sindresorhus/is-elevated) instead of [`is-root`](https://github.com/sindresorhus/is-root).

**Looking for feedback from Windows users.**

**Comment by sindresorhus** [comment]
@arthurvr @kevva @shinnn

**Comment by arthurvr** [comment]
I have honestly no idea if running things on windows as admin is as bad practice as running as root on unix but I guess I'm :+1:!

**Comment by silverwind** [comment]
The Windows Administrator isn't as powerful as root (It can't touch certain system files), and there's the issue that users who have UAC disabled are automatically admin, with no method to downgrade permissions that I know of.

**Comment by kevva** [comment]
Nah, I don't think you should block it on Windows. As @silverwind says it's not as powerful as the root user on Unix systems and it doesn't affect any functionality really.

**Comment by sindresorhus** [comment]
Alright. I thought Administrator user could screw up some permissions or something.

**Comment by silverwind** [comment]
Administrator can still do a lot like installing services and software, modifying program folder and more. It's only locked out from totally destroying the system, but even that can be circumvented by elevating to SYSTEM privileges theoretically. It's not safe at all ;)

**Comment by kevva** [comment]
Yeah, but isn't that the case for all users in the `Administrator` group?

**Comment by silverwind** [comment]
On a normal workstation with UAC enabled, a process runs unpriviledged and can elevate on demand by displaying the UAC prompt. And then there's 'Run as administrator' which is equivalent to a sudo.

If 'Run as administrator' can be detected and blocked, I'm all for it. But a tiny minority of users run with UAC disabled, which is basically 'sudo' for everything they run.

**Comment by kevva** [comment]
Yeah, first thing I'm doing on every Windows install is to disable UAC.

**Comment by silverwind** [comment]
Yeah, you'd be locked out of ever running a app that uses this module, unless we can detect if UAC is disabled.
