### ISSUE TITLE
Happy co-existence with logging frameworks

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/sudo-block#9]
I want to use [root-check](https://github.com/sindresorhus/root-check) in a project that uses [winston](https://github.com/winstonjs/winston) for logging. They don't really play well together due to the fact that downgrade-root does `console.errror()` followed by `process.exit()`, meaning that our logs don't contain any info about why the process died. winston is able to trap uncaught exceptions, but as far as I can tell, doesn't provide a built-in way to intercept `console.*` calls. I could hack this in by modifying `console.error`, but to most people that would seem abominable.

Another thought was to be able to provide something like a function (or implementation of `console`) to downgrade-root to do its business. Does any of this sound reasonable, and if not, any suggestions?

**Comment by sindresorhus** [comment]
Are you sure `winston` doesn't support listen to `console` calls? If so, sounds like a pretty big oversight for a logging framework. This might be relevant: https://github.com/winstonjs/winston/issues/228

You could maybe do a manual flush of the logs on `process.on('beforeExit')`.

**Comment by sholladay** [comment]
From Node's `beforeExit` docs:

> 'beforeExit' is not emitted for conditions causing explicit termination, such as process.exit() or uncaught exceptions ...

So, while I haven't actually tried it, that's not supposed to be possible. :(

Maybe the best I can do is listen for `process.on('exit')` and synchronously append something to the log file myself without the use of Winston, if the exit code matches what `sudo-block` does.

**Comment by sholladay** [comment]
Closing because, yeah, probably nothing should change here.
